export const PERMISSIONS = {
  DESIGN_CREATE: "DESIGN_CREATE",
  DESIGN_ASSIGN: "DESIGN_ASSIGN",
  DESIGN_ASSIGN_MANUAL: "DESIGN_ASSIGN_MANUAL",
  DESIGN_ASSIGN_AUTO: "DESIGN_ASSIGN_AUTO",
  DESIGN_REASSIGN: "DESIGN_REASSIGN",
  TASK_EXECUTE: "TASK_EXECUTE",
  TIME_VIEW_TEAM: "TIME_VIEW_TEAM",
  CORRECTION_RAISE: "CORRECTION_RAISE",
  CORRECTION_REQUEST: "CORRECTION_REQUEST",
  CORRECTION_EXECUTE: "CORRECTION_EXECUTE",
  CORRECTION_APPROVE: "CORRECTION_APPROVE",
  CORRECTION_REJECT: "CORRECTION_REJECT",
  DESIGN_APPROVE: "DESIGN_APPROVE",
  APPROVE_LEVEL_1: "APPROVE_LEVEL_1",
  APPROVE_SKETCH: "APPROVE_SKETCH",
  FINAL_APPROVE: "FINAL_APPROVE",
  MARK_LIVE: "MARK_LIVE",
  WORKFLOW_VIEW_HISTORY: "WORKFLOW_VIEW_HISTORY",
  COST_VIEW: "COST_VIEW",
  COST_ENTER: "COST_ENTER",
  KPI_ADMIN: "KPI_ADMIN",
  MASTER_ADMIN: "MASTER_ADMIN",
  PRODUCTION_RELEASE: "PRODUCTION_RELEASE",
  WORKFLOW_OVERRIDE: "WORKFLOW_OVERRIDE",
  /** Grey → Ready Stock shop-floor stages */
  ERP_FLOOR_OPERATE: "ERP_FLOOR_OPERATE",
  /** Sales + Sales Return */
  ERP_SALES_OPERATE: "ERP_SALES_OPERATE",
  /** Accounts / margin posting */
  ERP_ACCOUNTS_OPERATE: "ERP_ACCOUNTS_OPERATE",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_CODES = {
  DESIGN_HEAD: "DESIGN_HEAD",
  SKETCH_DESIGNER: "SKETCH_DESIGNER",
  PUNCHING_DESIGNER: "PUNCHING_DESIGNER",
  MACHINE_OPERATOR: "MACHINE_OPERATOR",
  SAMPLE_CHECKER: "SAMPLE_CHECKER",
  COSTING_TEAM: "COSTING_TEAM",
  PRODUCTION_HEAD: "PRODUCTION_HEAD",
  ADMIN: "ADMIN",
  MANAGEMENT: "MANAGEMENT",
} as const;

/** Legacy DESIGN_ASSIGN grants both manual and auto assign modes. */
export function hasAssignManualPermission(permissions: string[]): boolean {
  return (
    permissions.includes(PERMISSIONS.DESIGN_ASSIGN_MANUAL) ||
    permissions.includes(PERMISSIONS.DESIGN_ASSIGN)
  );
}

export function hasAssignAutoPermission(permissions: string[]): boolean {
  return (
    permissions.includes(PERMISSIONS.DESIGN_ASSIGN_AUTO) ||
    permissions.includes(PERMISSIONS.DESIGN_ASSIGN)
  );
}

export function hasCorrectionRequestPermission(permissions: string[]): boolean {
  return (
    permissions.includes(PERMISSIONS.CORRECTION_REQUEST) ||
    permissions.includes(PERMISSIONS.CORRECTION_RAISE)
  );
}

export function hasCorrectionExecutePermission(permissions: string[]): boolean {
  return (
    permissions.includes(PERMISSIONS.CORRECTION_EXECUTE) ||
    permissions.includes(PERMISSIONS.CORRECTION_RAISE) ||
    permissions.includes(PERMISSIONS.TASK_EXECUTE)
  );
}

export function hasCorrectionApprovePermission(permissions: string[]): boolean {
  return (
    permissions.includes(PERMISSIONS.CORRECTION_APPROVE) ||
    permissions.includes(PERMISSIONS.CORRECTION_RAISE) ||
    permissions.includes(PERMISSIONS.DESIGN_APPROVE)
  );
}

export function hasWorkflowHistoryPermission(permissions: string[]): boolean {
  return (
    permissions.includes(PERMISSIONS.WORKFLOW_VIEW_HISTORY) ||
    permissions.includes(PERMISSIONS.MASTER_ADMIN) ||
    hasPermission(permissions, DESIGN_LIST_VIEW_PERMISSIONS)
  );
}

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  [ROLE_CODES.DESIGN_HEAD]: [
    PERMISSIONS.DESIGN_CREATE,
    PERMISSIONS.DESIGN_ASSIGN,
    PERMISSIONS.DESIGN_ASSIGN_MANUAL,
    PERMISSIONS.DESIGN_ASSIGN_AUTO,
    PERMISSIONS.DESIGN_REASSIGN,
    PERMISSIONS.DESIGN_APPROVE,
    PERMISSIONS.APPROVE_SKETCH,
    PERMISSIONS.FINAL_APPROVE,
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.COST_ENTER,
    PERMISSIONS.CORRECTION_RAISE,
    PERMISSIONS.CORRECTION_REQUEST,
    PERMISSIONS.CORRECTION_EXECUTE,
    PERMISSIONS.CORRECTION_APPROVE,
    PERMISSIONS.CORRECTION_REJECT,
    PERMISSIONS.WORKFLOW_VIEW_HISTORY,
    PERMISSIONS.TIME_VIEW_TEAM,
    PERMISSIONS.WORKFLOW_OVERRIDE,
  ],
  [ROLE_CODES.SKETCH_DESIGNER]: [
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.CORRECTION_RAISE,
    PERMISSIONS.CORRECTION_EXECUTE,
  ],
  [ROLE_CODES.PUNCHING_DESIGNER]: [
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.CORRECTION_RAISE,
    PERMISSIONS.CORRECTION_EXECUTE,
  ],
  [ROLE_CODES.MACHINE_OPERATOR]: [PERMISSIONS.TASK_EXECUTE, PERMISSIONS.CORRECTION_EXECUTE],
  [ROLE_CODES.SAMPLE_CHECKER]: [
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.CORRECTION_RAISE,
    PERMISSIONS.CORRECTION_REQUEST,
    PERMISSIONS.CORRECTION_APPROVE,
    PERMISSIONS.CORRECTION_REJECT,
    PERMISSIONS.DESIGN_APPROVE,
    PERMISSIONS.APPROVE_LEVEL_1,
  ],
  [ROLE_CODES.COSTING_TEAM]: [
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.COST_ENTER,
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.ERP_ACCOUNTS_OPERATE,
  ],
  [ROLE_CODES.PRODUCTION_HEAD]: [
    PERMISSIONS.PRODUCTION_RELEASE,
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.ERP_FLOOR_OPERATE,
    PERMISSIONS.ERP_SALES_OPERATE,
    PERMISSIONS.MARK_LIVE,
  ],
  [ROLE_CODES.ADMIN]: Object.values(PERMISSIONS),
  [ROLE_CODES.MANAGEMENT]: [
    PERMISSIONS.DESIGN_APPROVE,
    PERMISSIONS.FINAL_APPROVE,
    PERMISSIONS.MARK_LIVE,
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.KPI_ADMIN,
    PERMISSIONS.TIME_VIEW_TEAM,
    PERMISSIONS.WORKFLOW_VIEW_HISTORY,
    PERMISSIONS.CORRECTION_APPROVE,
  ],
};

export function hasPermission(
  userPermissions: string[],
  required: PermissionCode | PermissionCode[],
): boolean {
  const requiredList = Array.isArray(required) ? required : [required];
  // Array = any of (OR). Single code = must have that permission.
  return requiredList.some((p) => userPermissions.includes(p));
}

/**
 * Who may browse the full design list / pipeline dashboards.
 * Executors (TASK_EXECUTE only) open designs via assigned tasks instead.
 */
export const DESIGN_LIST_VIEW_PERMISSIONS: PermissionCode[] = [
  PERMISSIONS.DESIGN_CREATE,
  PERMISSIONS.DESIGN_ASSIGN,
  PERMISSIONS.DESIGN_ASSIGN_MANUAL,
  PERMISSIONS.DESIGN_ASSIGN_AUTO,
  PERMISSIONS.TIME_VIEW_TEAM,
  PERMISSIONS.COST_VIEW,
  PERMISSIONS.PRODUCTION_RELEASE,
  PERMISSIONS.DESIGN_APPROVE,
  PERMISSIONS.KPI_ADMIN,
  PERMISSIONS.MASTER_ADMIN,
  PERMISSIONS.WORKFLOW_VIEW_HISTORY,
];

export const DESIGN_PIPELINE_VIEW_PERMISSIONS = DESIGN_LIST_VIEW_PERMISSIONS;

export function canListDesigns(permissions: string[]): boolean {
  return hasPermission(permissions, DESIGN_LIST_VIEW_PERMISSIONS);
}
