export const PERMISSIONS = {
  DESIGN_CREATE: "DESIGN_CREATE",
  DESIGN_ASSIGN: "DESIGN_ASSIGN",
  TASK_EXECUTE: "TASK_EXECUTE",
  TIME_VIEW_TEAM: "TIME_VIEW_TEAM",
  CORRECTION_RAISE: "CORRECTION_RAISE",
  DESIGN_APPROVE: "DESIGN_APPROVE",
  COST_VIEW: "COST_VIEW",
  KPI_ADMIN: "KPI_ADMIN",
  MASTER_ADMIN: "MASTER_ADMIN",
  PRODUCTION_RELEASE: "PRODUCTION_RELEASE",
  WORKFLOW_OVERRIDE: "WORKFLOW_OVERRIDE",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_CODES = {
  DESIGN_HEAD: "DESIGN_HEAD",
  SKETCH_DESIGNER: "SKETCH_DESIGNER",
  PUNCHING_DESIGNER: "PUNCHING_DESIGNER",
  MACHINE_OPERATOR: "MACHINE_OPERATOR",
  SAMPLE_CHECKER: "SAMPLE_CHECKER",
  COSTING_TEAM: "COSTING_TEAM",
  PRODUCTION_HEAD: "PRODUCTION_HEAD",
  ADMIN: "ADMIN",
  MANAGEMENT: "MANAGEMENT",
} as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  [ROLE_CODES.DESIGN_HEAD]: [
    PERMISSIONS.DESIGN_CREATE,
    PERMISSIONS.DESIGN_ASSIGN,
    PERMISSIONS.DESIGN_APPROVE,
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.CORRECTION_RAISE,
    PERMISSIONS.TIME_VIEW_TEAM,
    PERMISSIONS.WORKFLOW_OVERRIDE,
  ],
  [ROLE_CODES.SKETCH_DESIGNER]: [PERMISSIONS.TASK_EXECUTE, PERMISSIONS.CORRECTION_RAISE],
  [ROLE_CODES.PUNCHING_DESIGNER]: [PERMISSIONS.TASK_EXECUTE, PERMISSIONS.CORRECTION_RAISE],
  [ROLE_CODES.MACHINE_OPERATOR]: [PERMISSIONS.TASK_EXECUTE],
  [ROLE_CODES.SAMPLE_CHECKER]: [
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.CORRECTION_RAISE,
    PERMISSIONS.DESIGN_APPROVE,
  ],
  [ROLE_CODES.COSTING_TEAM]: [PERMISSIONS.COST_VIEW, PERMISSIONS.TASK_EXECUTE],
  [ROLE_CODES.PRODUCTION_HEAD]: [
    PERMISSIONS.PRODUCTION_RELEASE,
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.TASK_EXECUTE,
  ],
  [ROLE_CODES.ADMIN]: Object.values(PERMISSIONS),
  [ROLE_CODES.MANAGEMENT]: [
    PERMISSIONS.DESIGN_APPROVE,
    PERMISSIONS.TASK_EXECUTE,
    PERMISSIONS.COST_VIEW,
    PERMISSIONS.KPI_ADMIN,
    PERMISSIONS.TIME_VIEW_TEAM,
    PERMISSIONS.PRODUCTION_RELEASE,
  ],
};

export function hasPermission(
  userPermissions: string[],
  required: PermissionCode | PermissionCode[],
): boolean {
  const requiredList = Array.isArray(required) ? required : [required];
  // Array = any of (OR). Single code = must have that permission.
  return requiredList.some((p) => userPermissions.includes(p));
}
